server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fusionxpay-docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/?(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: '/?fusionxpay-(.*)'
        target_label: service
      - source_labels: [__meta_docker_container_name]
        regex: '/?fusionxpay-.*'
        action: keep
      - target_label: job
        replacement: fusionxpay-docker
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
    pipeline_stages:
      - docker: {}
      - regex:
          expression: '.*\b(?P<level>TRACE|DEBUG|INFO|WARN|ERROR)\b.*'
      - labels:
          level:
